// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/providers/nutanix/client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	converged "github.com/nutanix-cloud-native/prism-go-client/converged"
	v3 "github.com/nutanix-cloud-native/prism-go-client/v3"

	clusterModels "github.com/nutanix/ntnx-api-golang-clients/clustermgmt-go-client/v4/models/clustermgmt/v4/config"
	subnetModels "github.com/nutanix/ntnx-api-golang-clients/networking-go-client/v4/models/networking/v4/config"
	prismModels "github.com/nutanix/ntnx-api-golang-clients/prism-go-client/v4/models/prism/v4/config"
	imageModels "github.com/nutanix/ntnx-api-golang-clients/vmm-go-client/v4/models/vmm/v4/content"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetSubnet mocks base method.
func (m *MockClient) GetSubnet(ctx context.Context, uuid string) (*subnetModels.Subnet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnet", ctx, uuid)
	ret0, _ := ret[0].(*subnetModels.Subnet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnet indicates an expected call of GetSubnet.
func (mr *MockClientMockRecorder) GetSubnet(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnet", reflect.TypeOf((*MockClient)(nil).GetSubnet), ctx, uuid)
}

// ListSubnets mocks base method.
func (m *MockClient) ListSubnets(ctx context.Context, opts ...converged.ODataOption) ([]subnetModels.Subnet, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListSubnets", varargs...)
	ret0, _ := ret[0].([]subnetModels.Subnet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubnets indicates an expected call of ListSubnets.
func (mr *MockClientMockRecorder) ListSubnets(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubnets", reflect.TypeOf((*MockClient)(nil).ListSubnets), varargs...)
}

// GetImage mocks base method.
func (m *MockClient) GetImage(ctx context.Context, uuid string) (*imageModels.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, uuid)
	ret0, _ := ret[0].(*imageModels.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockClientMockRecorder) GetImage(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockClient)(nil).GetImage), ctx, uuid)
}

// ListImages mocks base method.
func (m *MockClient) ListImages(ctx context.Context, opts ...converged.ODataOption) ([]imageModels.Image, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListImages", varargs...)
	ret0, _ := ret[0].([]imageModels.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListImages indicates an expected call of ListImages.
func (mr *MockClientMockRecorder) ListImages(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImages", reflect.TypeOf((*MockClient)(nil).ListImages), varargs...)
}

// GetCluster mocks base method.
func (m *MockClient) GetCluster(ctx context.Context, uuid string) (*clusterModels.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCluster", ctx, uuid)
	ret0, _ := ret[0].(*clusterModels.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCluster indicates an expected call of GetCluster.
func (mr *MockClientMockRecorder) GetCluster(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCluster", reflect.TypeOf((*MockClient)(nil).GetCluster), ctx, uuid)
}

// ListClusters mocks base method.
func (m *MockClient) ListClusters(ctx context.Context, opts ...converged.ODataOption) ([]clusterModels.Cluster, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListClusters", varargs...)
	ret0, _ := ret[0].([]clusterModels.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClusters indicates an expected call of ListClusters.
func (mr *MockClientMockRecorder) ListClusters(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClusters", reflect.TypeOf((*MockClient)(nil).ListClusters), varargs...)
}

// ListAllHosts mocks base method.
func (m *MockClient) ListAllHosts(ctx context.Context, opts ...converged.ODataOption) ([]clusterModels.Host, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAllHosts", varargs...)
	ret0, _ := ret[0].([]clusterModels.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllHosts indicates an expected call of ListAllHosts.
func (mr *MockClientMockRecorder) ListAllHosts(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllHosts", reflect.TypeOf((*MockClient)(nil).ListAllHosts), varargs...)
}

// ListClusterPhysicalGPUs mocks base method.
func (m *MockClient) ListClusterPhysicalGPUs(ctx context.Context, clusterUUID string, opts ...converged.ODataOption) ([]clusterModels.PhysicalGpuProfile, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, clusterUUID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListClusterPhysicalGPUs", varargs...)
	ret0, _ := ret[0].([]clusterModels.PhysicalGpuProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClusterPhysicalGPUs indicates an expected call of ListClusterPhysicalGPUs.
func (mr *MockClientMockRecorder) ListClusterPhysicalGPUs(ctx, clusterUUID interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, clusterUUID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClusterPhysicalGPUs", reflect.TypeOf((*MockClient)(nil).ListClusterPhysicalGPUs), varargs...)
}

// ListClusterVirtualGPUs mocks base method.
func (m *MockClient) ListClusterVirtualGPUs(ctx context.Context, clusterUUID string, opts ...converged.ODataOption) ([]clusterModels.VirtualGpuProfile, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, clusterUUID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListClusterVirtualGPUs", varargs...)
	ret0, _ := ret[0].([]clusterModels.VirtualGpuProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClusterVirtualGPUs indicates an expected call of ListClusterVirtualGPUs.
func (mr *MockClientMockRecorder) ListClusterVirtualGPUs(ctx, clusterUUID interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, clusterUUID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClusterVirtualGPUs", reflect.TypeOf((*MockClient)(nil).ListClusterVirtualGPUs), varargs...)
}

// GetCategory mocks base method.
func (m *MockClient) GetCategory(ctx context.Context, uuid string) (*prismModels.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategory", ctx, uuid)
	ret0, _ := ret[0].(*prismModels.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory.
func (mr *MockClientMockRecorder) GetCategory(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockClient)(nil).GetCategory), ctx, uuid)
}

// ListCategories mocks base method.
func (m *MockClient) ListCategories(ctx context.Context, opts ...converged.ODataOption) ([]prismModels.Category, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListCategories", varargs...)
	ret0, _ := ret[0].([]prismModels.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockClientMockRecorder) ListCategories(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockClient)(nil).ListCategories), varargs...)
}

// ListAllProject mocks base method.
func (m *MockClient) ListAllProject(ctx context.Context, filter string) (*v3.ProjectListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllProject", ctx, filter)
	ret0, _ := ret[0].(*v3.ProjectListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllProject indicates an expected call of ListAllProject.
func (mr *MockClientMockRecorder) ListAllProject(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllProject", reflect.TypeOf((*MockClient)(nil).ListAllProject), ctx, filter)
}
